"""
Django settings for chikapedia project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from .settings_common import *
from pathlib import Path
from .local_settings import SECRET_KEY as sk
from .local_settings import ALLOWED_HOSTS as ah

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

SECRET_KEY = sk
ALLOWED_HOSTS = ah

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
